import { CartCountProvider } from '#/components/cart-count-context';
import { Header } from '#/components/header';
import { Sidebar } from '#/components/sidebar';
import { Metadata } from 'next';
// import { GeistSans } from 'geist/font/sans';
// import './globals.css';
// this'd be auto-generated by running critters or something alike
// (we'd still load link rel=stylesheet for unreferenced things in the initial HTML)
import criticalCss from '#/lib/criticalCss';

export const metadata: Metadata = {
  metadataBase: new URL('https://partialprerendering.com'),
  title: 'Next.js Partial Prerendering',
  description: 'A demo of Next.js using Partial Prerendering.',
  openGraph: {
    title: 'Next.js Partial Prerendering',
    description: 'A demo of Next.js using Partial Prerendering.',
  },
  twitter: {
    card: 'summary_large_image',
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  // <html lang="en" className={`[color-scheme:dark] ${GeistSans.variable}`}>
  return (
    <html lang="en" className={`__variable_343187 [color-scheme:dark]`}>
      <body className="overflow-y-scroll bg-gray-1100 bg-[url('/grid.svg')] pb-36">
        <style
          dangerouslySetInnerHTML={{ __html: criticalCss }}
          data-critical-css
        />
        <Sidebar />
        <div className="lg:pl-72">
          <div className="mx-auto max-w-4xl space-y-8 px-2 pt-20 lg:px-8 lg:py-8">
            <div className="rounded-lg bg-vc-border-gradient p-px shadow-lg shadow-black/20">
              <div className="rounded-lg bg-black p-3.5 lg:p-6">
                <CartCountProvider>
                  <div className="space-y-10">
                    <Header />

                    {children}
                  </div>
                </CartCountProvider>
              </div>
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}
